pipeline {
    agent any

    stages {


        stage('checkout') {
            steps {
                git url: 'https://github.com/gowda123chandu/course-jenkins-project.git', branch: 'main'
                sh "ls-lrt"    
                }
        }


        stage('setup'){
            steps{
                sh "pip install -r requirements.txt"
            
            }
        }
        stage('Test') {
            steps {
                sh "pytest"
                
            }
        }    
        stage('Deployment') {
            input {
                message "Do you want to proceed further"
                ok "Yes"
            }
            steps {
                echo "Running Deployment"
                
            }
        } 
        
            
    }
}
