pipeline {
    agent any

    environment {
        SERVER_IP = credentials('prod-vm-ip')
        PASSWORD = credentials('password')
    }

    stages {
        stage('Setup') {
            steps {
                sh "pip install -r requirements.txt"
            }
        }
        stage('Test') {
            steps {
                sh "pytest"
            }
        }

        stage('Package code') {
            steps {
                sh "zip -r myapp.zip ./* -x '*.git*'"
                sh "ls -lart"
            }
        }

        stage('Deploy to Prod') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'prod-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    script {
                        // Use sshpass to connect via password authentication
                        sh '''
                        # Copy the app.zip file to the remote server
                        sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no myapp.zip $USERNAME@$SERVER_IP:/home/$USERNAME/

                        # SSH into the server and deploy the app
                        sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP << EOF
                            # Unzip the application
                            unzip -o /home/$USERNAME/myapp.zip -d /home/$USERNAME/app/

                            # Set up virtual environment and install dependencies
                            cd /home/$USERNAME/app/
                            python3 -m venv venv
                            bash -c "source venv/bin/activate && ls -lart && pip install -r requirements.txt"

                            # Restart the service
                            sudo systemctl restart flaskapp.service
                        EOF
                        '''
                    }
                }
            }
        }
    }
}
