pipeline {
    agent any

    environment {
        SERVER_IP = credentials('prod-vm-ip')
        PASSWORD = credentials('password')
    }

    stages {
        stage('Setup') {
            steps {
                // Set up the virtual environment and install requirements on the Jenkins agent (local machine)
                sh """
                pip3 install --user -r 02-single-server-deployment/requirements.txt  --break-system-packages
                """
            }
        }

        stage('Test') {
            steps {
                // Run tests (you may adjust this as per your test framework)
                sh """
                pytest
                """
            }
        }

        stage('Package code') {
            steps {
                // Create a zip of the project excluding the .git directory
                sh """
                zip -r myapp.zip ./* -x '*.git*'
                ls -lart
                """
            }
        }

        stage('Deploy to Prod') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'password', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    script {
                        // Use sshpass to connect via password authentication
                        sh '''
                        # Copy the app.zip file to the remote server
                        sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no myapp.zip $USERNAME@$SERVER_IP:/home/$USERNAME/

                        # SSH into the server and deploy the app
                        sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP << EOF
                            # Unzip the application
                            unzip -o /home/$USERNAME/myapp.zip -d /home/$USERNAME/app/

                            # Set up virtual environment and install dependencies
                            cd /home/$USERNAME/app/
                            python3 -m venv venv
                            bash -c 'source venv/bin/activate && pip install -r requirements.txt'

                            # Restart the service
                            sudo systemctl restart flaskapp.service
                        EOF
                        '''
                    }
                }
            }
        }
    }
}
