pipeline {
    agent any

    environment {
        SERVER_IP = credentials('prod-vm-ip')
    }
    stages {
        stage('Setup') {
            steps {
                sh "pip install -r requirements.txt"
            }
        }
        stage('Test') {
            steps {
                sh "pytest"
            }
        }

        stage('Package code') {
            steps {
                sh "zip -r myapp.zip ./* -x '*.git*'"
                sh "ls -lart"
            }
        }

        stage('Deploy to Prod') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'password', passwordVariable: 'password', usernameVariable: 'password')]) {
                    sh '''
                    sshpass -p $PASSWORD -o StrictHostKeyChecking=no myapp.zip  ${username}@${SERVER_IP}:/home/azureuser/
                    sshpass -p $PASSWORD -o StrictHostKeyChecking=no ${username}@${SERVER_IP} << EOF
                        unzip -o /home/azureuser/myapp.zip -d /home/ec2-user/app/
                        source app/venv/bin/activate
                        cd /home/azureuser/app/
                        pip install -r requirements.txt
                        sudo systemctl restart flaskapp.service
EOF
                    '''
                }
            }
        }
       
        
       
        
    }
}
